### PR TITLE
Use moto sagemaker client for tests

### PR DESCRIPTION
**Pull request by Bougeant**

### CODE REVIEW

**Comment by Bougeant** [comment]
@hodgestar, I'm pretty sad to remove all this code but I believe that's what you had in mind? 😉

**Comment by hodgestar** [comment]
Moto got a SageMaker fixture? That is great!

**Comment by Bougeant** [comment]
I can't believe that you basically created your own sagemaker moto for this repo! 🙃

**Review by hodgestar — APPROVED** [review]

**Comment by hodgestar** [comment]
> I can't believe that you basically created your own sagemaker moto for this repo! upside_down_face

Well, we needed it. :)

**Pull request merged**
