### PR TITLE
Pin flask version

### PR DESCRIPTION
**Pull request by KyleHarrison**

### CODE REVIEW

**Review by hodgestar — APPROVED** [review]
Good idea!

I hope this didn't bite too badly while deploying. :/

**Comment by hodgestar** [comment]
Not sure why the tests are suddenly failing with a different output from the tests for what happens when no model is specified. Maybe a click version issue?

**Comment by KyleHarrison** [comment]
Thanks!  This was the start of my attempt at fixing a repo currently breaking which is using ml2p.

'
[2021-05-13T09:49:35.161Z] ImportError while loading conftest '/app/tests/conftest.py'.
[2021-05-13T09:49:35.161Z] tests/conftest.py:5: in <module>
[2021-05-13T09:49:35.161Z]     from .fixtures import (  # noqa: imported so that pytest can find the fixtures
[2021-05-13T09:49:35.161Z] tests/fixtures.py:13: in <module>
[2021-05-13T09:49:35.161Z]     from ml2p.core import SageMakerEnv
[2021-05-13T09:49:35.161Z] .tox/py3.6/lib/python3.6/site-packages/ml2p/core.py:23: in <module>
[2021-05-13T09:49:35.161Z]     from .errors import LocalEnvError
[2021-05-13T09:49:35.161Z] .tox/py3.6/lib/python3.6/site-packages/ml2p/errors.py:6: in <module>
[2021-05-13T09:49:35.161Z]     from flask_api.exceptions import APIException
[2021-05-13T09:49:35.161Z] .tox/py3.6/lib/python3.6/site-packages/flask_api/__init__.py:1: in <module>
[2021-05-13T09:49:35.161Z]     from flask_api.app import FlaskAPI
[2021-05-13T09:49:35.161Z] .tox/py3.6/lib/python3.6/site-packages/flask_api/app.py:4: in <module>
[2021-05-13T09:49:35.161Z]     from flask._compat import reraise, string_types, text_type
[2021-05-13T09:49:35.161Z] E   ModuleNotFoundError: No module named 'flask._compat'
`
This made me assume since Flask recently did a major version update this would be an easy fix. I will checkout click now!

**Comment by KyleHarrison** [comment]
Great, was the click upgrade as well!

**Comment by KyleHarrison** [comment]
All good with a merge and minor version release?

**Review by hodgestar — COMMENTED** [review]
Approved!

**Pull request merged**
